# Site
name: 'مدرسه دانجو'
description: 'مدرسه آنلاین'
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.png'
baseurl: '/'
disqus: ''
email: 'mhkarami9b7@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives 
 
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: default
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    
authors:
    sal:
      name:           mhk
      site:           https://danjoo.ir
      avatar:         /assets/images/favicon.png
      bio:            "دانجو"
      email:          mhkarami97@gmail.com
      twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]